# Artificial Neural Network
1. A set of nodes -> each node has input and output
2. Each node performes some computation => node function/ activation function

- AND
- OR
- XNOR
- XOR

## 1. AND

In [17]:
def update_weight(target, a, W_old, b_old, p):
    e = target - a
    W_new = W_old + e*p
    b_new = b_old + e
    return W_new, b_new

In [18]:
def calc_and(Weight, b, p):
    p = np.transpose(p)
    a = np.dot(Weight, p) + b
    print(a)
    if a > 1.5:
        a = 1
    else:
        a = 0
    return a

In [19]:
import numpy as np
W = np.array([1.0, 0.8])
b = 0.1

p1 = np.array([1, 1])
t1 = 1
p2 = np.array([1, 0])
t2 = 0
p3 = np.array([0, 1])
t3 = 0
p4 = np.array([0, 0])
t4 = 0

In [20]:
a1 = calc_and(W, b, p1)
W, b = update_weight(t1, a1, W, b, p1)
W, b

1.9000000000000001


(array([1. , 0.8]), 0.1)

In [21]:
a2 = calc_and(W, b, p2)
W, b = update_weight(t2, a2, W, b, p2)
W, b

1.1


(array([1. , 0.8]), 0.1)

In [22]:
a3 = calc_and(W, b, p3)
W, b = update_weight(t3, a3, W, b, p3)
W, b

0.9


(array([1. , 0.8]), 0.1)

In [23]:
a4 = calc_and(W, b, p4)
W, b = update_weight(t4, a4, W, b, p4)
W, b

0.1


(array([1. , 0.8]), 0.1)

In [24]:
x = calc_and(W, b, np.array([1, 1]))
x

1.9000000000000001


1

## 2. OR

In [919]:
import numpy as np
W = np.array([1, 1])
b = 0.6

p1 = np.array([1, 1])
t1 = 1
p2 = np.array([1, 0])
t2 = 1
p3 = np.array([0, 0])
t3 = 0
p4 = np.array([0, 1])
t4 = 1

In [925]:
def calc_or(Weight, b, p):
    p = np.transpose(p)
    a = np.dot(Weight, p) + b
    print(a)
    if a < 1:
        a = 0
    else:
        a = 1
    return a

In [926]:
a1 = calc_or(W, b, p1)
W, b = update_weight(t1, a1, W, b, p1)
W, b

1.6


(array([1, 1]), -0.4)

In [927]:
a2 = calc_or(W, b, p2)
W, b = update_weight(t2, a2, W, b, p2)
W, b

0.6


(array([2, 1]), 0.6)

In [928]:
a3 = calc_or(W, b, p3)
W, b = update_weight(t3, a3, W, b, p3)
W, b

0.6


(array([2, 1]), 0.6)

In [929]:
a4 = calc_or(W, b, p4)
W, b = update_weight(t4, a4, W, b, p4)
W, b

1.6


(array([2, 1]), 0.6)

In [934]:
x = calc_or(W, b, np.array([0, 0]))
x

0.6


0

## 3. X-OR

In [856]:
import numpy as np
W = np.array([1.5, -0.5])
b = 0.8

p1 = np.array([1, 1])
t1 = 0
p2 = np.array([1, 0])
t2 = 1
p3 = np.array([0, 0])
t3 = 0
p4 = np.array([0, 1])
t4 = 1

In [857]:
def calc_xor(Weight, b, p):
    p = np.transpose(p)
    a = np.dot(Weight, p) + b
    print(a)
    if a < 2 and a > 0.5:
        a = 0
    else:
        a = 1
    print(a)
    return a

In [858]:
a1 = calc_xor(W, b, p1)
W, b = update_weight(t1, a1, W, b, p1)
W, b

1.8
0


(array([ 1.5, -0.5]), 0.8)

In [859]:
a2 = calc_xor(W, b, p2)
W, b = update_weight(t2, a2, W, b, p2)
W, b

2.3
1


(array([ 1.5, -0.5]), 0.8)

In [860]:
a3 = calc_xor(W, b, p3)
W, b = update_weight(t3, a3, W, b, p3)
W, b

0.8
0


(array([ 1.5, -0.5]), 0.8)

In [861]:
a4 = calc_xor(W, b, p4)
W, b = update_weight(t4, a4, W, b, p4)
W, b

0.30000000000000004
1


(array([ 1.5, -0.5]), 0.8)

In [862]:
x = calc_xor(W, b, np.array([1, 0]))

2.3
1


## 3. X-NOR

In [863]:
import numpy as np
W = np.array([0.5, 0.6])
b = 0.5

p1 = np.array([1, 1])
t1 = 1
p2 = np.array([1, 0])
t2 = 0
p3 = np.array([0, 0])
t3 = 1
p4 = np.array([0, 1])
t4 = 0

In [864]:
def calc_xnor(Weight, b, p):
    p = np.transpose(p)
    a = np.dot(Weight, p) + b
    print(a)
#     if a > 0:
#         a = 1
#     else:
#         a = 0
    return a

In [865]:
a1 = calc_xnor(W, b, p1)
W, b = update_weight(t1, a1, W, b, p1)
W, b

1.6


(array([-1.00000000e-01, -1.11022302e-16]), -0.10000000000000009)

In [866]:
a2 = calc_xnor(W, b, p2)
W, b = update_weight(t2, a2, W, b, p2)
W, b

-0.20000000000000018


(array([ 1.00000000e-01, -1.11022302e-16]), 0.10000000000000009)

In [867]:
a3 = calc_xnor(W, b, p3)
W, b = update_weight(t3, a3, W, b, p3)
W, b

0.10000000000000009


(array([ 1.00000000e-01, -1.11022302e-16]), 1.0)

In [868]:
a4 = calc_xnor(W, b, p1)
W, b = update_weight(t4, a4, W, b, p4)
W, b

1.1


(array([ 0.1, -1.1]), -0.10000000000000009)

In [869]:
x = calc_xnor(W, b, np.array([1, 0]))
x

0.0


0.0